Fix failing

diff --git a/.github/workflows/surveycat-api-ci-cd.yml b/.github/workflows/surveycat-api-ci-cd.yml
--- a/.github/workflows/surveycat-api-ci-cd.yml
+++ b/.github/workflows/surveycat-api-ci-cd.yml
@@ -9,7 +9,7 @@ jobs:
   build_push_deploy:
     runs-on: ubuntu-latest
     env:
-      IMAGE_VERSION: "2.17"
+      IMAGE_VERSION: "2.18"
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -105,9 +105,9 @@ jobs:
         run: |
           ssh -p 54222 -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr 'docker-compose -f /var/www/surveycat_api/docker-compose.prod.yml exec -T surveycat-api-apache sh -c "retry=0; while ! nc -z localhost 40000 && [ $retry -lt 60 ]; do sleep 5; retry=$((retry+1)); done"'
 
-      - name: Run database migrations and seed
+      - name: Check database connection and run migrations and seed
         run: |
-          ssh -p 54222 -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr 'docker-compose -f /var/www/surveycat_api/docker-compose.prod.yml exec --no-TTY surveycat-api-apache php artisan migrate:fresh --seed > /var/www/surveycat_api/migration.log 2>&1 || cat /var/www/surveycat_api/migration.log'
+          ssh -p 54222 -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr 'docker-compose -f /var/www/surveycat_api/docker-compose.prod.yml exec -T surveycat-api-apache php artisan migrate:fresh || echo "Database connection failed or migrations did not run successfully."'
 
       - name: Set directories permissions
         run: |
