Add My Profile

diff --git a/.github/workflows/surveycat-api-ci-cd.yml b/.github/workflows/surveycat-api-ci-cd.yml
--- a/.github/workflows/surveycat-api-ci-cd.yml
+++ b/.github/workflows/surveycat-api-ci-cd.yml
@@ -9,7 +9,7 @@ jobs:
   build_push_deploy:
     runs-on: ubuntu-latest
     env:
-      IMAGE_VERSION: "2.52"
+      IMAGE_VERSION: "2.53"
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -98,6 +98,10 @@ jobs:
       - name: Check database connection and run migrations and seed
         run: |
           ssh -p 54222 -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr 'docker-compose -f /var/www/surveycat_api/docker-compose.prod.yml exec -T surveycat-api-apache php artisan migrate:fresh --force --seed || echo "Database connection failed or migrations did not run successfully."'
+
+      - name: Create or Update Storage Link
+        run: |
+          ssh -p 54222 -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr 'docker-compose -f /var/www/surveycat_api/docker-compose.prod.yml exec -T surveycat-api-apache php artisan storage:link --force || echo "Storage link command failed, but continuing deployment."'
 
       - name: Set directories permissions
         run: |
